### PR TITLE
[FEAT] Add security code from UCLA - Do NOT merge to main - release 3.

### PR DESCRIPTION
**Pull request by GportDev**

### CODE REVIEW

**Comment by tntech-ngin** [comment]
We will merge this in the next release.

**Comment by tntech-ngin** [comment]
@tianyuan129 Can you review this? Thanks.

**Comment by tntech-ngin** [comment]
@tianyuan129 Did you get a chance to look at this?

**Comment by tntech-ngin** [comment]
Can we make the security parameters optional and define default values in the config file?

**Comment by tntech-ngin** [comment]
Where are we verifying the signatures? I can't find it.

**Review by tianyuan129 — APPROVED** [review]
Have you tried? Did it run? It seems no major change beyond my code.

**Comment by tianyuan129** [comment]
> Where are we verifying the signatures? I can't find it.

It's in the SVS package. This need to also merge the [SVS part](https://github.com/tianyuan129/ndn-python-svs) to work: security is on the SVS published data. My code is to patch the hydra to work with my security patched SVS package

**Comment by tntech-ngin** [comment]
@GportDev Can you please rebase?

**Comment by tntech-ngin** [comment]
@GportDev Can you please rebase?

**Pull request closed without merging**
