### PR TITLE
Fix/data deletion

### LINKED ISSUE #52: [Urgent] Improve fetch performance
We can bring the whole set of packets into memory when the first request comes in.
When the last segment is requested, we free the memory.
We can also keep a counter of last request and decide when it is time to delete it from memory.

This changes will need to happen somewhere around here:
https://github.com/tntech-ngin/ndn-hydra/blob/54157d313c3c20f0ccb794fe413d4c852fb650a2/ndn_hydra/repo/handles/read_handle.py#L101

### PR DESCRIPTION
**Pull request by sankalpatimilsina12**
Closes #52 

In progress.

Adds: Caching. Cache names are now simple key strings for faster fetches. The caches get collected by garbage collector.

The bottleneck seems not to be DB after tests. I am investigating this further.

Tests:
I think we can ignore the caching all together, the tests seem to show that DB fetches are quite fast, will look more.

### CODE REVIEW

**Comment by tntech-ngin** [comment]
It seems we are adding a bunch of binary files in the "files" directory. Please remove.

We can merge the other changes and test.

**Comment by sankalpatimilsina12** [comment]
I was not able to locate the `files` directory, it was previously present in the `examples` directory which is no longer there. Could you please let me know where the `files` directory is? @tntech-ngin

**Comment by tntech-ngin** [comment]
Okay - merging.

**Comment by tntech-ngin** [comment]
@sankalpatimilsina12 @xai990 @GportDev Merged, please test.

**Pull request merged**
